spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/summonerInfo"
    username: summoner
    password: summoner
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db.changelog/liquibase-changelog.xml

riot:
  api-key: "ur key"
  url: https://ru.api.riotgames.com

feign:
  summoner-api:
    url: ${riot.url}
    path: /lol/summoner/v4/summoners
  champion-mastery-api:
    url: ${riot.url}
    path: /lol/champion-mastery/v4
  spectator-api:
    url: ${riot.url}
    path: /lol/spectator/v4